version: '2'
services:
  nginx:
    image: openresty/openresty
    hostname: nginx
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
    env_file:
      - ./docker/nginx/nginx.env
      - ./.env
    volumes:
      - ./docker/nginx/logs/:/usr/local/openresty/nginx/logs
      - ./docker/nginx/etc/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./docker/nginx/etc/conf.d:/usr/local/openresty/nginx/conf/conf.d
    depends_on:
      - node
  node:
    image: node
    hostname: ${NODE_HOST}
    container_name: ${NODE_HOST}
    env_file:
      - ./docker/node.js/node.env
      - ./docker/mysql/mysql.env
      - ./.env
    command: node --harmony docker/nodemon/index.js
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "5858:5858"
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - mysql
      - mongo
      - redis
  mysql:
    image: mysql
    hostname: ${DB_HOST}
    container_name: ${DB_HOST}
    env_file:
      - ./docker/mysql/mysql.env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/etc:/etc/mysql/conf.d
  redis:
    image: redis
    hostname: ${REDIS_HOST}
    container_name: ${REDIS_HOST}
    volumes:
      - ./docker/redis/data:/dataz
  mongo:
    image: mongo
    hostname: ${MONGO_HOST}
    container_name: ${MONGO_HOST}
    volumes:
      - ./docker/mongo/data:/data/db
      - ./docker/mongo/etc/mongod.conf.orig:/etc/mongod.conf.orig