version: '2'
services:
  web:
    container_name: node-app
    image: node
    ports:
      - "3000:3000"
      - "5858:5858"
    volumes:
      - .:/code
    command: node --harmony --debug  app.js
    dns:
      - 176.80.80.80
      - 8.8.8.8
    env_file:
      - ./node.env
    working_dir: /code
    links:
     - db
     - redis
     - mongo
    depends_on:
     - redis
     - db
     - mongo
  redis:
    image: redis
    env_file:
      - ./redis.env
    volumes:
      - .data/redis/data:/data
    command: redis-server --requirepass node-app
  db:
    image: mysql
    env_file:
     - ./mysql.env
    volumes:
     - .data/mysql/data/:/var/lib/mysql
     - .data/mysql/etc:/etc/mysql/conf.d
  mongo:
   image: mongo
   volumes:
     - .data/mongo/data:/data/db