version: '2'
services:
  web:
    container_name: node.js
    image: node
    env_file:
      - ./docker/node.js/node.env
      - ./docker/mysql/mysql.env
      - ./docker/.env
    command: node --harmony --debug  app.js
    ports:
      - "3000:3000"
      - "5858:5858"
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - mysql
      - mongo
      - redis
  mysql:
    container_name: ${DB_HOST}
    image: mysql
    env_file:
      - ./docker/mysql/mysql.env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/etc:/etc/mysql/conf.d
  redis:
    image: redis
    container_name: ${REDIS_HOST}
    volumes:
      - ./docker/redis/data:/data
  mongo:
    image: mongo
    container_name: ${MONGO_HOST}
    volumes:
      - ./docker/mongo/data:/data/db